version: '3'

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"

  blackjack-service:
    build: ./blackjack-service
    environment:
      SPRING_PROFILES_ACTIVE: prod
      MONGO_URI: mongodb://mongodb:27017/apexon
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
  
  blackjack-frontend:
    build: ./blackjack-frontend
    ports:
      - "3000:3000"
    depends_on:
      - blackjack-service
